// <auto-generated />
namespace MyCompany.MyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Created_Table_PlayersAndMaps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_Table_PlayersAndMaps));
        
        string IMigrationMetadata.Id
        {
            get { return "202103190212260_Created_Table_PlayersAndMaps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
